### ISSUE TITLE
Error in terminal when refreshing PDP page

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-next-starterkit#105]
## Issue

When reloading the PDP page (cmd + r) I get the following error in terminal

```
web_1  | Warning: Failed prop type: The prop `serverState` is marked as required in `WithData(WithCatalogItem)`, but its value is `undefined`.
web_1  |     in WithData(WithCatalogItem) (at withShop.js:34)
web_1  | apollo client error { TypeError: Cannot read property 'apollo' of undefined
web_1  |     at new WithData (/usr/local/src/reaction-app/src/.next/dist/bundles/pages/product.js:5755:42)
web_1  |     at walkTree (/usr/local/src/reaction-app/node_modules/react-apollo/react-apollo.umd.js:34:38)
web_1  |     at walkTree (/usr/local/src/reaction-app/node_modules/react-apollo/react-apollo.umd.js:66:25)
web_1  |     at getPromisesFromTree (/usr/local/src/reaction-app/node_modules/react-apollo/react-apollo.umd.js:96:9)
web_1  |     at getDataFromTree (/usr/local/src/reaction-app/node_modules/react-apollo/react-apollo.umd.js:109:24)
web_1  |     at /usr/local/src/reaction-app/node_modules/react-apollo/react-apollo.umd.js:117:45
web_1  |     at <anonymous>
web_1  |     at process._tickDomainCallback (internal/process/next_tick.js:228:7) queryErrors: [ [Circular] ] }
```

**Comment by aldeed** [comment]
Haven't seen this in awhile, so I'm closing.
