### ISSUE TITLE
SSR does not seem to be working

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/reaction-next-starterkit#182]
SSR does not seem to be working. The root request for the home page has a response that does not include the html for the grid. The response has an empty root element: `<div id="__next"></div>` see image below.

<img width="1336" alt="empty_response" src="https://user-images.githubusercontent.com/486340/43019339-77f2b03a-8c11-11e8-8a17-f3bdf615684c.png">

Further, I see 5 GraphQL requests on initial page load, they `primaryShopId`, `shopQuery`,`tagsQuery` and `catalogItemsQuery`. These should have been executed on the server. See image below.

<img width="1317" alt="requests" src="https://user-images.githubusercontent.com/486340/43019488-063f3a7a-8c12-11e8-9be5-fb34f6e1225c.png">

**Comment by spencern** [comment]
I'm able to reproduce this. I'm also seeing that most (all?) of the data we should need to render the page exists in the Apollo State 
```
{
  "props": {
    "apolloState": {
      "cookies": {
        "i18next": "en",
        "token": "r5VxN5xR6S9-rJSvHe2nsrpRmOS8_1R_-2n509ZnKtd"
      },
      "ROOT_QUERY": {
        "primaryShopId": "cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==",
        "shop({\"id\":\"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==\"})": {
          "type": "id",
          "generated": false,
          "id": "Shop:cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==",
          "typename": "Shop"
        },
        "tags({\"shopId\":\"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==\",\"first\":200})": {
          "type": "id",
          "generated": true,
          "id":
            "$ROOT_QUERY.tags({\"shopId\":\"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==\",\"first\":200})",
          "typename": "TagConnection"
        },
        "catalogItems({\"shopIds\":[\"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==\"],\"first\":20,\"sortBy\":\"updatedAt\",\"sortByPriceCurrencyCode\":\"USD\",\"sortOrder\":\"desc\"})": {
          "type": "id",
          "generated": true,
          "id":
            "$ROOT_QUERY.catalogItems({\"shopIds\":[\"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==\"],\"first\":20,\"sortBy\":\"updatedAt\",\"sortByPriceCurrencyCode\":\"USD\",\"sortOrder\":\"desc\"})",
          "typename": "CatalogItemConnection"
        }
      },
      "Shop:cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==": {
        "_id": "cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==",
        "description": null,
        "name": "Reaction",
        "currency": {
          "type": "id",
          "generated": true,
          "id": "$Shop:cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==.currency",
          "typename": "Currency"
        },
        "__typename": "Shop"
      },
      "$Shop:cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==.currency": {
        "code": "USD",
        "__typename": "Currency"
      },
      "$ROOT_QUERY.tags({\"shopId\":\"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==\",\"first\":200}).pageInfo": {
        "endCursor": "cnBqQ3ZUQkdqaEJpMnhkcm8=",
        "startCursor": "Y3NlQ0JTU3JKM3Q4SFFTTlA=",
        "hasNextPage": false,
        "__typename": "PageInfo"
      },
      "$ROOT_QUERY.tags({\"shopId\":\"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==\",\"first\":200})": {
        "pageInfo": {
          "type": "id",
          "generated": true,
          "id":
            "$ROOT_QUERY.tags({\"shopId\":\"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==\",\"first\":200}).pageInfo",
          "typename": "PageInfo"
        },
        "edges": [
          {
            "type": "id",
            "generated": true,
            "id":
              "$ROOT_QUERY.tags({\"shopId\":\"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==\",\"first\":200}).edges.0",
            "typename": "TagEdge"
          },
          {
            "type": "id",
            "generated": true,
            "id":
              "$ROOT_QUERY.tags({\"shopId\":\"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==\",\"first\":200}).edges.1",
            "typename": "TagEdge"
          }
        ],
        "__typename": "TagConnection"
      },
      "$ROOT_QUERY.tags({\"shopId\":\"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==\",\"first\":200}).edges.0": {
        "cursor": "Y3NlQ0JTU3JKM3Q4SFFTTlA=",
        "node": {
          "type": "id",
          "generated": false,
          "id": "Tag:cmVhY3Rpb24vdGFnOmNzZUNCU1NySjN0OEhRU05Q",
          "typename": "Tag"
        },
        "__typename": "TagEdge"
      },
      "Tag:cmVhY3Rpb24vdGFnOmNzZUNCU1NySjN0OEhRU05Q": {
        "_id": "cmVhY3Rpb24vdGFnOmNzZUNCU1NySjN0OEhRU05Q",
        "position": null,
        "name": "example-product",
        "slug": "example-product",
        "isTopLevel": false,
        "subTagIds": { "type": "json", "json": [] },
        "heroMediaUrl": null,
        "__typename": "Tag"
      },
      "$ROOT_QUERY.tags({\"shopId\":\"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==\",\"first\":200}).edges.1": {
        "cursor": "cnBqQ3ZUQkdqaEJpMnhkcm8=",
        "node": {
          "type": "id",
          "generated": false,
          "id": "Tag:cmVhY3Rpb24vdGFnOnJwakN2VEJHamhCaTJ4ZHJv",
          "typename": "Tag"
        },
        "__typename": "TagEdge"
      },
      "Tag:cmVhY3Rpb24vdGFnOnJwakN2VEJHamhCaTJ4ZHJv": {
        "_id": "cmVhY3Rpb24vdGFnOnJwakN2VEJHamhCaTJ4ZHJv",
        "position": null,
        "name": "Shop",
        "slug": "shop",
        "isTopLevel": true,
        "subTagIds": { "type": "json", "json": [] },
        "heroMediaUrl": null,
        "__typename": "Tag"
      },
      "$ROOT_QUERY.catalogItems({\"shopIds\":[\"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==\"],\"first\":20,\"sortBy\":\"updatedAt\",\"sortByPriceCurrencyCode\":\"USD\",\"sortOrder\":\"desc\"})": {
        "totalCount": 1,
        "pageInfo": {
          "type": "id",
          "generated": true,
          "id":
            "$ROOT_QUERY.catalogItems({\"shopIds\":[\"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==\"],\"first\":20,\"sortBy\":\"updatedAt\",\"sortByPriceCurrencyCode\":\"USD\",\"sortOrder\":\"desc\"}).pageInfo",
          "typename": "PageInfo"
        },
        "edges": [
          {
            "type": "id",
            "generated": true,
            "id":
              "$ROOT_QUERY.catalogItems({\"shopIds\":[\"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==\"],\"first\":20,\"sortBy\":\"updatedAt\",\"sortByPriceCurrencyCode\":\"USD\",\"sortOrder\":\"desc\"}).edges.0",
            "typename": "CatalogItemEdge"
          }
        ],
        "__typename": "CatalogItemConnection"
      },
      "$ROOT_QUERY.catalogItems({\"shopIds\":[\"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==\"],\"first\":20,\"sortBy\":\"updatedAt\",\"sortByPriceCurrencyCode\":\"USD\",\"sortOrder\":\"desc\"}).pageInfo": {
        "endCursor": "Q01KUW9pWkZLaGdXbmtYdVk=",
        "startCursor": "Q01KUW9pWkZLaGdXbmtYdVk=",
        "hasNextPage": false,
        "hasPreviousPage": false,
        "__typename": "PageInfo"
      },
      "$ROOT_QUERY.catalogItems({\"shopIds\":[\"cmVhY3Rpb24vc2hvcDpKOEJocTN1VHRkZ3daeDNyeg==\"],\"first\":20,\"sortBy\":\"updatedAt\",\"sortByPriceCurrencyCode\":\"USD\",\"sortOrder\":\"desc\"}).edges.0": {
        "cursor": "Q01KUW9pWkZLaGdXbmtYdVk=",
        "node": {
          "type": "id",
          "generated": false,
          "id":
            "CatalogItemProduct:cmVhY3Rpb24vY2F0YWxvZ0l0ZW06Q01KUW9pWkZLaGdXbmtYdVk=",
          "typename": "CatalogItemProduct"
        },
        "__typename": "CatalogItemEdge"
      },
      "CatalogItemProduct:cmVhY3Rpb24vY2F0YWxvZ0l0ZW06Q01KUW9pWkZLaGdXbmtYdVk=": {
        "_id": "cmVhY3Rpb24vY2F0YWxvZ0l0ZW06Q01KUW9pWkZLaGdXbmtYdVk=",
        "product": {
          "type": "id",
          "generated": false,
          "id":
            "CatalogProduct:cmVhY3Rpb24vY2F0YWxvZ1Byb2R1Y3Q6QkNUTVo2SFR4RlNwcEpFU2s=",
          "typename": "CatalogProduct"
        },
        "__typename": "CatalogItemProduct"
      },
      "CatalogProduct:cmVhY3Rpb24vY2F0YWxvZ1Byb2R1Y3Q6QkNUTVo2SFR4RlNwcEpFU2s=": {
        "_id": "cmVhY3Rpb24vY2F0YWxvZ1Byb2R1Y3Q6QkNUTVo2SFR4RlNwcEpFU2s=",
        "title": "Basic Reaction Product",
        "slug": "basic-reaction-product",
        "description":
          "Sign in as administrator to edit.\nYou can clone this product from the product grid.\nYou can upload images click or drag in image box on the left here.\nTag this product below, and then add tag in navigation.\nClick the bookmark in the tag to set product url.\nOption variants, price, quantity, and child variants are created by clicking on the variant below, clone the variant to add more options.\nDetails can be added below the image for more specific product information.\n Login next to the cart, and then click the dashboard icon for more tools.",
        "vendor": "Example Manufacturer",
        "isLowQuantity": false,
        "isSoldOut": false,
        "isBackorder": false,
        "shop": {
          "type": "id",
          "generated": true,
          "id":
            "$CatalogProduct:cmVhY3Rpb24vY2F0YWxvZ1Byb2R1Y3Q6QkNUTVo2SFR4RlNwcEpFU2s=.shop",
          "typename": "Shop"
        },
        "pricing": [
          {
            "type": "id",
            "generated": true,
            "id":
              "CatalogProduct:cmVhY3Rpb24vY2F0YWxvZ1Byb2R1Y3Q6QkNUTVo2SFR4RlNwcEpFU2s=.pricing.0",
            "typename": "ProductPricingInfo"
          }
        ],
        "primaryImage": null,
        "__typename": "CatalogProduct"
      },
      "$CatalogProduct:cmVhY3Rpb24vY2F0YWxvZ1Byb2R1Y3Q6QkNUTVo2SFR4RlNwcEpFU2s=.shop.currency": {
        "code": "USD",
        "__typename": "Currency"
      },
      "$CatalogProduct:cmVhY3Rpb24vY2F0YWxvZ1Byb2R1Y3Q6QkNUTVo2SFR4RlNwcEpFU2s=.shop": {
        "currency": {
          "type": "id",
          "generated": true,
          "id":
            "$CatalogProduct:cmVhY3Rpb24vY2F0YWxvZ1Byb2R1Y3Q6QkNUTVo2SFR4RlNwcEpFU2s=.shop.currency",
          "typename": "Currency"
        },
        "__typename": "Shop"
      },
      "$CatalogProduct:cmVhY3Rpb24vY2F0YWxvZ1Byb2R1Y3Q6QkNUTVo2SFR4RlNwcEpFU2s=.pricing.0.currency": {
        "code": "USD",
        "__typename": "Currency"
      },
      "CatalogProduct:cmVhY3Rpb24vY2F0YWxvZ1Byb2R1Y3Q6QkNUTVo2SFR4RlNwcEpFU2s=.pricing.0": {
        "currency": {
          "type": "id",
          "generated": true,
          "id":
            "$CatalogProduct:cmVhY3Rpb24vY2F0YWxvZ1Byb2R1Y3Q6QkNUTVo2SFR4RlNwcEpFU2s=.pricing.0.currency",
          "typename": "Currency"
        },
        "displayPrice": "$12.99 - $19.99",
        "minPrice": 12.99,
        "maxPrice": 19.99,
        "__typename": "ProductPricingInfo"
      }
    }
  },
  "page": "/",
  "pathname": "/",
  "query": {},
  "buildId": "-",
  "assetPrefix": "",
  "runtimeConfig": {
    "externalAssetsUrl": "http://localhost:3000",
    "graphqlUrl": "http://localhost:3030/graphql-alpha",
    "segmentAnalytics": { "skipMinimize": false },
    "placeholderImageUrls": {},
    "keycloakConfig": {}
  },
  "nextExport": false,
  "err": null,
  "chunks": []
}
```

**Comment by mikemurray** [comment]
The following error displayed in Terminal. It would seem like, either something is wrong with the initialization of the Apollo client in lib, wither with the `withApollo` decorator or the `initApollo` helper.

```
web_1  | [Network error]: FetchError: request to http://devserver.reaction-api:3030/graphql-alpha failed, reason: connectECONNREFUSED 172.18.0.2:3030
web_1  | Error while running `getDataFromTree` { Error: Network error: request to http://devserver.reaction-api:3030/graphql-alpha failed, reason: connect ECONNREFUSED 172.18.0.2:3030
web_1  |     at new ApolloError (/usr/local/src/node_modules/src/errors/ApolloError.ts:56:5)
web_1  |     at /usr/local/src/node_modules/src/core/QueryManager.ts:489:31
web_1  |     at /usr/local/src/node_modules/src/core/QueryManager.ts:1028:11
web_1  |     at Array.forEach (<anonymous>)
web_1  |     at /usr/local/src/node_modules/src/core/QueryManager.ts:1027:10
web_1  |     at Map.forEach (<anonymous>)
web_1  |     at QueryManager.broadcastQueries (/usr/local/src/node_modules/src/core/QueryManager.ts:1021:18)
web_1  |     at /usr/local/src/node_modules/src/core/QueryManager.ts:388:18
web_1  |     at <anonymous>
web_1  |     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
web_1  |   graphQLErrors: [],
web_1  |   networkError:
web_1  |    { FetchError: request to http://devserver.reaction-api:3030/graphql-alpha failed, reason: connect ECONNREFUSED 172.18.0.2:3030
web_1  |     at ClientRequest.<anonymous> (/usr/local/src/node_modules/node-fetch/index.js:133:11)
web_1  |     at emitOne (events.js:116:13)
web_1  |     at ClientRequest.emit (events.js:211:7)
web_1  |     at Socket.socketErrorListener (_http_client.js:387:9)
web_1  |     at emitOne (events.js:116:13)
web_1  |     at Socket.emit (events.js:211:7)
web_1  |     at emitErrorNT (internal/streams/destroy.js:64:8)
web_1  |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
web_1  |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
web_1  |      name: 'FetchError',
web_1  |      message: 'request to http://devserver.reaction-api:3030/graphql-alpha failed, reason: connect ECONNREFUSED 172.18.0.2:3030',
web_1  |      type: 'system',
web_1  |      errno: 'ECONNREFUSED',
web_1  |      code: 'ECONNREFUSED' },
web_1  |   message: 'Network error: request to http://devserver.reaction-api:3030/graphql-alpha failed, reason: connect ECONNREFUSED 172.18.0.2:3030',
web_1  |   extraInfo: undefined,
web_1  |   queryErrors: [ [Circular] ] }
```
