### ISSUE TITLE
[bug] TypeError: Cannot read property '_id' of null of PDP

### ISSUE THREAD

**Issue by jeffcorpuz** [reactioncommerce/reaction-next-starterkit#485]
Type: **critical**
Bug Type: **blocker**

**Describe the bug**
Going to the PDP of any product except the default Reaction product causes a read error.

**To Reproduce**
1. Either use sample data or create a new product from an empty db in core
2. Click on any product that is not the default reaction product
3. Verify error.

**Expected behavior**
Able to go to PDP of any given product.

**Screenshots**
<img width="1440" alt="screen shot 2019-01-19 at 10 52 17 am" src="https://user-images.githubusercontent.com/6117033/51418569-5dacc380-1bd8-11e9-8703-143703a6a10c.png">

**Logs**
Browser Console:
```
Uncaught TypeError: Cannot read property '_id' of null
    at ProductDetail.js:241
    at Array.find (<anonymous>)
    at ProductDetail.render (ProductDetail.js:241)
    at allowStateChanges (mobx.module.js:235)
    at index.module.js:741
    at trackDerivedFunction (mobx.module.js:3277)
    at Reaction.push.../../node_modules/mobx/lib/mobx.module.js.Reaction.track (mobx.module.js:3481)
    at ProductDetail.reactiveRender [as render] (index.module.js:736)
    at ProductDetail.makeComponentReactive (index.module.js:805)
    at ProductDetail.target.render (index.module.js:923)
    at finishClassComponent (react-dom.development.js:13194)
    at updateClassComponent (react-dom.development.js:13156)
    at beginWork (react-dom.development.js:13825)
    at performUnitOfWork (react-dom.development.js:15864)
    at workLoop (react-dom.development.js:15903)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at invokeGuardedCallback (react-dom.development.js:187)
    at replayUnitOfWork (react-dom.development.js:15311)
    at renderRoot (react-dom.development.js:15963)
    at performWorkOnRoot (react-dom.development.js:16561)
    at performWork (react-dom.development.js:16483)
    at performSyncWork (react-dom.development.js:16455)
    at requestWork (react-dom.development.js:16355)
    at scheduleWork$1 (react-dom.development.js:16219)
    at Object.enqueueForceUpdate (react-dom.development.js:11337)
    at Query.Component.forceUpdate (react.development.js:288)
    at Query._this.updateCurrentData (react-apollo.browser.umd.js:314)
    at Object.next (react-apollo.browser.umd.js:296)
    at notifySubscription (Observable.js:126)
    at onNotify (Observable.js:161)
    at SubscriptionObserver.next (Observable.js:215)
    at ObservableQuery.js:398
    at Array.forEach (<anonymous>)
    at Object.next (ObservableQuery.js:398)
    at QueryManager.js:417
    at QueryManager.js:755
    at Array.forEach (<anonymous>)
    at QueryManager.js:754
    at Map.forEach (<anonymous>)
    at QueryManager.push.../../node_modules/apollo-client/core/QueryManager.js.QueryManager.broadcastQueries (QueryManager.js:749)
    at Object.next (QueryManager.js:795)
    at notifySubscription (Observable.js:126)
    at onNotify (Observable.js:161)
    at SubscriptionObserver.next (Observable.js:215)
    at dedupLink.js:57
    at Array.forEach (<anonymous>)
    at Object.next (dedupLink.js:57)
    at notifySubscription (Observable.js:126)
    at onNotify (Observable.js:161)
```

____
Terminal:
```Attempting silent re-auth
{ Error: Network error: Unexpected token U in JSON at position 0
    at new ApolloError (/usr/local/src/node_modules/apollo-client/bundle.umd.js:121:32)
    at /usr/local/src/node_modules/apollo-client/bundle.umd.js:1188:45
    at /usr/local/src/node_modules/apollo-client/bundle.umd.js:1619:21
    at Array.forEach (<anonymous>)
    at /usr/local/src/node_modules/apollo-client/bundle.umd.js:1618:22
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/usr/local/src/node_modules/apollo-client/bundle.umd.js:1613:26)
    at /usr/local/src/node_modules/apollo-client/bundle.umd.js:1115:35
    at process._tickCallback (internal/process/next_tick.js:68:7)
  graphQLErrors: [],
  networkError:
   { SyntaxError: Unexpected token U in JSON at position 0
       at JSON.parse (<anonymous>)
       at /usr/local/src/node_modules/apollo-link-http-common/lib/bundle.umd.js:45:29
       at process._tickCallback (internal/process/next_tick.js:68:7)
     response:
      Body {
        url: 'http://reaction.api.reaction.localhost:3000/graphql-alpha',
        status: 401,
        statusText: 'Unauthorized',
        headers: [Headers],
        ok: false,
        body: [PassThrough],
        bodyUsed: true,
        size: 0,
        timeout: 0,
        _raw: [Array],
        _abort: false,
        _bytes: 12 },
     statusCode: 401,
     bodyText: 'Unauthorized' },
  message: 'Network error: Unexpected token U in JSON at position 0',
  extraInfo: undefined }
Warning: <title> should not be used in _document.js's <Head>. https://err.sh/next.js/no-document-title
Warning: <title> should not be used in _document.js's <Head>. https://err.sh/next.js/no-document-title
Warning: <title> should not be used in _document.js's <Head>. https://err.sh/next.js/no-document-title
> Building page: /product```

**Additional context**
Reaction : release-2.0.0-rc.9 (#483)
Platform : release-2.0.0-rc.9 (https://github.com/reactioncommerce/reaction-platform/pull/46)

**Comment by jeffcorpuz** [comment]
@kieckhafer thanks for the clear-up. Solved by doing a restart.
