### ISSUE TITLE
wierd error  apollo graphql 400 error

### ISSUE THREAD

**Issue by MoustafaBayommy** [reactioncommerce/reaction-next-starterkit#486]
Unable to access the GraphQL API. 

Is it running and accessible at http://localhost:3000/graphql-alpha from the Storefront UI server.

```
Unable to access the GraphQL API. Is it running and accessible at http://localhost:3000/graphql-alpha from the Storefront UI server?
{ Error: Network error: Response not successful: Received status code 400
    at new ApolloError (/home/moustafabauommy/Desktop/WORK/reaction-platform/reaction-next-starterkit/node_modules/apollo-client/bundle.umd.js:99:32)
    at /home/moustafabauommy/Desktop/WORK/reaction-platform/reaction-next-starterkit/node_modules/apollo-client/bundle.umd.js:967:45
    at /home/moustafabauommy/Desktop/WORK/reaction-platform/reaction-next-starterkit/node_modules/apollo-client/bundle.umd.js:1329:21
    at Array.forEach (<anonymous>)
    at /home/moustafabauommy/Desktop/WORK/reaction-platform/reaction-next-starterkit/node_modules/apollo-client/bundle.umd.js:1328:22
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/home/moustafabauommy/Desktop/WORK/reaction-platform/reaction-next-starterkit/node_modules/apollo-client/bundle.umd.js:1323:26)
    at /home/moustafabauommy/Desktop/WORK/reaction-platform/reaction-next-starterkit/node_modules/apollo-client/bundle.umd.js:917:35
    at process._tickCallback (internal/process/next_tick.js:68:7)
  graphQLErrors: [],
  networkError:
   { ServerError: Response not successful: Received status code 400
       at throwServerError (/home/moustafabauommy/Desktop/WORK/reaction-platform/reaction-next-starterkit/node_modules/apollo-link-http-common/lib/bundle.umd.js:36:21)
       at /home/moustafabauommy/Desktop/WORK/reaction-platform/reaction-next-starterkit/node_modules/apollo-link-http-common/lib/bundle.umd.js:64:17
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'ServerError',
     response:
      Body {
        url: 'http://localhost:3000/graphql-alpha',
        status: 400,
        statusText: 'Bad Request',
        headers: [Headers],
        ok: false,
        body: [Gunzip],
        bodyUsed: true,
        size: 0,
        timeout: 0,
        _raw: [Array],
        _abort: false,
        _bytes: 171 },
     statusCode: 400,
     result: { errors: [Array] } },
  message:
   'Network error: Response not successful: Received status code 400',
  extraInfo: undefined }
[GraphQL error]: Message: Cannot query field "displayTitle" on type "Tag"., Location: [{"line":36,"column":3}], Path: undefined```

**Comment by jeffcorpuz** [comment]
Hi @MoustafaBayommy thank you for this report. 

____

Just a few questions: 

What are the steps did you take to reach this issue?
What version of starter-kit are you running?
 Are you using `reaction-platform`?

**Comment by MoustafaBayommy** [comment]
Hi @jeffcorpuz  
this error raise when running inside docker container or in my machine . i am using reaction-platform  for initial setting up  .
i am on  Ubuntu  using node v10  using starter-kit   v0.1.0 .

i was very conviced about  hydra should i register or create client on hydra first then update the client secret and id fist to . env in starter-kit?

**Comment by kieckhafer** [comment]
@MoustafaBayommy Have you resolved this issue? It seems like your API container (the one running at port 3000) was shut off, this is usually when this error occurs. If you restart the API container, this error should go away.

**Comment by MoustafaBayommy** [comment]
@kieckhafer  yes it has been solved after i re make the whole reaction  platform

**Comment by kieckhafer** [comment]
@moustafabayommy has stated this was resolved. Closing.
